.PHONY: clean All

All:
	@echo "----------Building project:[ Bool - Debug ]----------"
	@cd "Bool" && "$(MAKE)" -f  "Bool.mk"
clean:
	@echo "----------Cleaning project:[ Bool - Debug ]----------"
	@cd "Bool" && "$(MAKE)" -f  "Bool.mk" clean
